on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build executable
        run: cd prng && cargo build --release
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-generators
          path: prng/target/release/prng.exe
